-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cursos
(
    id integer NOT NULL DEFAULT nextval('cursos_id_seq'::regclass),
    nome character varying(60) COLLATE pg_catalog."default" NOT NULL,
    descricao character varying(60) COLLATE pg_catalog."default" NOT NULL,
    imagen pg_snapshot NOT NULL,
    status boolean NOT NULL,
    CONSTRAINT cursos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.professor
(
    id integer NOT NULL DEFAULT nextval('professor_id_seq'::regclass),
    nome character varying(20) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(16) COLLATE pg_catalog."default" NOT NULL,
    email character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_login PRIMARY KEY (id)
);
END;